# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArgoCompare < Formula
  desc "A comparison tool for displaying the differences between ArgoCD Applications in different Git branches"
  homepage "https://github.com/shini4i/argo-compare"
  version "0.2.0"
  license "MIT"

  depends_on "helm"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shini4i/argo-compare/releases/download/v0.2.0/argo-compare_0.2.0_Darwin_arm64.tar.gz"
      sha256 "338f960e73528e4215c7035024f472117dc85bb13f785f10437c2cee13946f3e"

      def install
        bin.install "argo-compare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shini4i/argo-compare/releases/download/v0.2.0/argo-compare_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "ab046a45336727a08408df39f71317ba17a8115637b93454f5ea45fd767268ea"

      def install
        bin.install "argo-compare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shini4i/argo-compare/releases/download/v0.2.0/argo-compare_0.2.0_Linux_x86_64.tar.gz"
      sha256 "ea6a68fdb854b0428cc4976ad1d5d51781e77a5733a9ab13934e7d317e72834e"

      def install
        bin.install "argo-compare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shini4i/argo-compare/releases/download/v0.2.0/argo-compare_0.2.0_Linux_arm64.tar.gz"
      sha256 "859f1247134f6b0b6f5637e174a7e7286fbea2991a9495bd97abb45caa8db400"

      def install
        bin.install "argo-compare"
      end
    end
  end
end
