# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kd < Formula
  desc "Simple script for kubernetes secrets decoding"
  homepage "https://github.com/shini4i/kd"
  url "https://github.com/shini4i/kd/archive/v0.1.3.tar.gz"
  sha256 "0b992ae1e96ffb9a2ebcb0dd75c1bb3943a503006757517a43a322934fd55feb"
  license "MIT"

  depends_on "kubernetes-cli"
  depends_on "yq"

  def install
    bin.install "src/kd.sh" => "kd"
  end
end
