# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kd < Formula
  desc "Bash script that makes it easy to view the contents of secrets stored in a kub"
  homepage "https://github.com/shini4i/kd"
  url "https://github.com/shini4i/kd/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "3a571f82c7da39f7d3b35566daf5818b8073de9d7cf6cb366a41480a73f02d69"
  license "MIT"

  depends_on "kubernetes-cli"
  depends_on "yq"

  def install
    bin.install "src/kd.sh" => "kd"
  end
end
