# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kd < Formula
  desc "Simple script for kubernetes secrets decoding"
  homepage "https://github.com/shini4i/kd"
  url "https://github.com/shini4i/kd/archive/v0.1.1.tar.gz"
  sha256 "e16504587ae55d12a148c857496171ae05c28d2589d61164c4484a1ee9af36b7"
  license "MIT"

  depends_on "kubernetes-cli"
  depends_on "yq"

  def install
    bin.install "kd" => "kd"
  end
end
