# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KubeconfigGenerator < Formula
  desc "Simple script for generating kubeconfig for a provided service account"
  homepage "https://github.com/shini4i/kubeconfig-generator"
  url "https://github.com/shini4i/kubeconfig-generator/archive/v0.1.1.tar.gz"
  sha256 "b240791afb63246a1aa85155ceb41c4999d59d181741b962514616ef5b476d30"
  license "MIT"

  depends_on "kubernetes-cli"

  def install
    bin.install "src/kubeconfig-generator.sh" => "kubeconfig-generator"
  end
end
