# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KubeconfigGenerator < Formula
  desc "Simple script for generating kubeconfig for a provided service account"
  homepage "https://github.com/shini4i/kubeconfig-generator"
  url "https://github.com/shini4i/kubeconfig-generator/archive/v0.1.0.tar.gz"
  sha256 "eb8649825060570917ebd75408ecec278ba5bd81bfb026a971433ccf0dfd14da"
  license "MIT"

  def install
    bin.install "src/kubeconfig-generator.sh" => "kubeconfig-generator"
  end
end
