# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class KubeconfigGenerator < Formula
  desc "Simple script for generating kubeconfig for a provided service account"
  homepage "https://github.com/shini4i/kubeconfig-generator"
  url "https://github.com/shini4i/kubeconfig-generator/archive/v0.1.3.tar.gz"
  sha256 "736dad37c927e8bbefd7111b882a813b5c260aeebd1f4b6f04e29fb7db05d7f6"
  license "MIT"

  depends_on "kubernetes-cli"

  def install
    bin.install "src/kubeconfig-generator.sh" => "kubeconfig-generator"
  end
end
