# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PreCommitMakefile < Formula
  desc "A tool that parses Makefile targets and automatically updates the project's README with a list of available targets and their descriptions"
  homepage "https://github.com/shini4i/pre-commit-makefile"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shini4i/pre-commit-makefile/releases/download/v0.2.2/pre-commit-makefile_0.2.2_darwin_arm64.tar.gz"
      sha256 "e5fe0d90a7361406a1b5531cedd2ef62bb162979c9a820c3d1814deb5b2ddb2d"

      def install
        bin.install "pre-commit-makefile"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shini4i/pre-commit-makefile/releases/download/v0.2.2/pre-commit-makefile_0.2.2_darwin_amd64.tar.gz"
      sha256 "c9fdc8a485add36114c0ee250194d1a735d93ccc71ca0b1f080177de45195a71"

      def install
        bin.install "pre-commit-makefile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shini4i/pre-commit-makefile/releases/download/v0.2.2/pre-commit-makefile_0.2.2_linux_arm64.tar.gz"
      sha256 "836c3e0c36bcadab605ac9da09d054263c66ecdea37c6e16b91004176f169b66"

      def install
        bin.install "pre-commit-makefile"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shini4i/pre-commit-makefile/releases/download/v0.2.2/pre-commit-makefile_0.2.2_linux_amd64.tar.gz"
      sha256 "9bfb4f9b521921c21d49b624f4ef2cc6765a2f7874e7aefccb4c19aebba394b1"

      def install
        bin.install "pre-commit-makefile"
      end
    end
  end
end
